version: '3'
services:
  build:
    image: cwhimura/elixir:v1.6.0-rc.1
    volumes:
      - .:/work
      - .mix:/root/.mix
      - ~/.atom/packages/ide-elixir/elixir-ls-release:/erl_libs
      - .:${PWD} # for language-server
